### ISSUE TITLE
"Raised" value display

### ISSUE THREAD

**Issue by AlexSQY** [OpenSats/website#10]
Hello,
Donated through https://opensats.org/projects/opensats_legal_defense
After some operation the project page displayed "Raised 420,.. BTC".
The value did not fit my donation, I thus suppose it was the complete raised amount.
Perhaps there is a glitch or bug somewhere?
Regards,
A.

**Comment by AlexSQY** [comment]
Figure for today funding is rather ~1.13BTC thus it would be the max for this project opened today.
(just published by OpenSats on twitter)

**Comment by futurepaul** [comment]
was testing some fake values and that slipped through, now have an api for real values. thank you!
