### ISSUE TITLE
minor HTML issue

### ISSUE THREAD

**Issue by statusquont** [OpenSats/website#11]
On: https://opensats.org/faq

The Answer to Q: "How much of my donation goes towards individuals and projects supported by Open Sats?" ends in "(thanks to our generous donors) &lt;—- link donor page"

Using Chrome Version 104.0.5112.81

![chrome_OpenSats_-_Google_Chrome_FXSVy5hB9d](https://user-images.githubusercontent.com/15948511/185567716-feea0216-05b4-4376-964a-c0ec49cbf47c.png)

**Comment by futurepaul** [comment]
thank you!
