### ISSUE TITLE
[Donation Form] Change BTCPay Server default payment method to Lightning

### ISSUE THREAD

**Issue by chris-bayly-per** [OpenSats/website#130]
Current checkout defaults to on-chain. Unless a majority of donors are using that, it may make sense to change that to default to Lightning.

**Comment by dergigi** [comment]
Thank you for tracking this!

Lightning is the default & on-chain is only enabled for donations of $20+. I just double-checked the settings and tested it. I'm not sure when this was set up, so it might have not been the case when you tracked the issue. 

Closing as complete.
