### ISSUE TITLE
Add Visual Indicator: Project cards for bitcoin/nostr/lightning

### ISSUE THREAD

**Issue by Arvin21M** [OpenSats/website#174]
### This is about the Listed Project cards. 

We need a way to easily indicate which project is related to which protocol (Bitcoin, Nostr, or Lightning).

Per @dergigi 
> ...what I'm thinking is a small colored bottom border or something for nostr/bitcoin/lightning (purple, orange, yellow) - or something that makes it obvious what kind of category that project is.

**Other options:**

1. Small logo/icon of a Bitcoin B (orange), Lightning bolt (yellow), or Ostrich head for nostr (purple) next to the Project/Company name or "by line".
2. A glowing border around the entire card for each project, with the related protocol color at ~50% transparency.
3. The donate button for each project card is a solid color of the associated protocol, or a glowing outline around the donate button only.

 
### Listed Project Cards (Dark Mode)
![image](https://github.com/OpenSats/website/assets/141419722/5803d0e6-7d34-4ca6-8f6e-2552aea04021)

### Listed Projects Cards (Light Mode)
![image](https://github.com/OpenSats/website/assets/141419722/889614e2-d993-4535-86e9-3b7ca6be150d)

### **Side note/thought:**

- Some of the donate buttons are uneven with one another due to one project have a longer description than the other. I propose anchoring the donate button and details link to the bottom of each card so its static.
![image](https://github.com/OpenSats/website/assets/141419722/89e0062b-5995-4e94-a941-71d3d4e5d3cb)

Let me know how I can help.

Thank you.

**Comment by dergigi** [comment]
Thanks for tracking this @Arvin21M!

> Some of the donate buttons are uneven with one another due to one project have a longer description than the other.

I agree, that should definitely be improved.

---

@moteanup24 I'm not a designer, so I'd say try out various things and see what looks good and feels right. Something simple and subtle, orange/purple/yellow is what I have in mind personally, but feel free to come up with something. As long as it doesn't look out-of-place with the current look & feel we're good.

**Comment by moteanup24** [comment]
@dergigi @Arvin21M 

Just doing a final review before pushing some changes--add colored labels to project cards, and standardize project card length to align donate and 'visit' buttons across cards.

Here is a preview (note that I added a "Nostr" tag randomly to a project just to show you how it would render, as it appears that none of the existing projects have a Nostr tag).

Just doing some cleaning up and other checks before pushing but let me know if you have any comments!

![Screenshot from 2023-11-09 09-31-15](https://github.com/OpenSats/website/assets/126610837/10cd95f0-7616-40c5-bf37-abdfe7b7a240)

**Comment by moteanup24** [comment]
Sure I will play around with that. My concern with just having a color indicator (whether as a border or background) was whether the association back to protocols would be clear enough to viewers. 

On second look though, I agree the cards are getting busy.

**Comment by Arvin21M** [comment]
> Apologies for being vague on this, but would you mind trying something more subtle? Like a 2-3px bottom border or coloring the background slightly.
> 
> I think having explicit "tag" elements is too much on these cards, they are already overloaded as is. People don't know where to click. Even the donate button is probably too much.

Thought to chime in here with a question about this... What if the project is working on more than one protocol (ie: Bitcoin (orange) and Lightning (yellow)? How will the colored border thing work for these cases, just pick one they are known best for?

**Comment by moteanup24** [comment]
@dergigi 

Opinion on the current bottom border color implementation? Again I just added a 'Nostr' tag randomly to illustrate the rendering.

Re @Arvin21M 's point I'm hesitant to incorporate more than one color, even though some projects have both Bitcoin and Lightning tagged. I've currently implemented the following logic: 

if (tags contains Nostr), then purple
if (tags contains Lightning), then yellow
if (tags contains Bitcoin), then orange

The assumptions being that Lightning implies Bitcoin and Nostr and Bitcoin/Lightning are mutually exclusive.

![Screenshot from 2023-11-09 10-57-19](https://github.com/OpenSats/website/assets/126610837/44898663-bfd8-4aa0-92d5-d10896d636df)
