### ISSUE TITLE
Add Possibility to Filter: opensats.org/projects

### ISSUE THREAD

**Issue by Arvin21M** [OpenSats/website#175]
### This is about adding filtering capabilities for Listed Projects on [opensats.org/projects](https://opensats.org/projects)

Per @dergigi 
> "...a filter that uses the tags we already have would be great, again that would be nostr/bitcoin/lightning but also wallet/etc - we have that data already... (https://flowbite.com/blocks/application/filter/#advanced-filter-by-keywords) Something like that."

![image](https://github.com/OpenSats/website/assets/141419722/f710c69f-c7dc-4126-8524-b8216bdeab66)

**Comment by dergigi** [comment]
Can be something simple at first, a nostr/bitcoin/lightning filter would go a long way already. We have `tags` defined already, so simply use those.

https://github.com/OpenSats/website/blob/2aeeaba853f4ca77175ccb77959e174f640a0c9b/data/projects/zeus.mdx#L13
