### ISSUE TITLE
Visual Indicators For Project Cards in Dark Mode Not Working

### ISSUE THREAD

**Issue by Arvin21M** [OpenSats/website#194]
@dergigi and @moteanup24 

Visual indicators distinguishing between Bitcoin, Nostr, or Lightning Projects are not working in Dark Mode. See screenshots below taken from Google Chrome Desktop. Let me know how I can help. Thank you:

![image](https://github.com/OpenSats/website/assets/141419722/06966794-cf76-453d-b05e-d7944abf0817)

![image](https://github.com/OpenSats/website/assets/141419722/7aedca78-644e-4681-bc7d-24ac28b1ce29)

**Comment by moteanup24** [comment]
Strange, I thought I checked for that before. Will look into it. Thanks!

**Comment by moteanup24** [comment]
@Arvin21M submitting PR to implement the following:

![image](https://github.com/OpenSats/website/assets/126610837/f11f75f9-d534-4e27-b97d-13bec377858a)

**Comment by Arvin21M** [comment]
Looks great @moteanup24 !
I'll close this Issue out.
Feel free to re-open if necessary.
