### ISSUE TITLE
Allow sats as a currency option

### ISSUE THREAD

**Issue by Kukks** [OpenSats/website#41]
There was a bounty denominated in sats for some btcpayserver feature, and I directed them to pay on opensats but the currency was only in USD. While btcpay can handle multi-currency without issues, your internal reporting might go nuts?

**Comment by dergigi** [comment]
Agree, for the scenario you described it would probably make sense to have a fiat/sats switch that will change the denominator here:

![Screenshot 2023-05-02 at 09 46 20](https://user-images.githubusercontent.com/109058/235609140-e090484f-e454-4400-8de5-20307aa67aa4.png)

**Comment by Bayernatoor** [comment]
If this is still something we want I can give it a shot. Seems like a good idea.

**Comment by Bayernatoor** [comment]
Currently working on this one.
