### ISSUE TITLE
Lightning misconfiguration on btcpay

### ISSUE THREAD

**Issue by Kukks** [OpenSats/website#42]
I believe there may be some misconfiguration on the lightning settings on the btcpayserver store as amountless invoices are not showing lightning as an option.

Expected settingsL
![image](https://user-images.githubusercontent.com/1818366/230397790-7224ebc0-8a49-48b5-a4df-4839707e3967.png)

Additionally, you should configure the minimum threshold for onchain so that users arent prompted to pay <few thousand sats on chain which the fees would eat up

**Comment by dergigi** [comment]
Thanks, I'll have a look.

**Comment by MatulefM** [comment]
I'm not sure if this is related to or a separate issue.  I went to donate today and the BTC Payserver would not create an invoice. 

![Screenshot_20230501-072101](https://user-images.githubusercontent.com/99508106/235451194-253c976d-b4ca-4267-91e9-5c4615d3c402.png)

**Comment by dergigi** [comment]
Thanks for reporting @Kukks, I think the settings are fixed now.

- Lightning = default
- Zero-amount invoices now allow for Lightning
- Onchain disabled for small amounts

**Comment by MatulefM** [comment]
> Please try again @MatulefM, not sure what was wrong.
> 
> I managed to generate multiple invoices just now.

Working great 👍
