### ISSUE TITLE
Update Sponsor Section of Home Page

### ISSUE THREAD

**Issue by abitcoinperson** [OpenSats/website#82]
- [x] Remove Silvergate Bank
- [x] Update Link for Andrew Blair to direct to: https://www.poynerspruill.com/professionals/andy-blair/ 
- [x] Add "Unchained" , their new logo (Unchained Logo) and direct to: https://unchained.com
- [x] Update "The Bitcoin Company" logo to the attached TBC Logo file
![TBC Logo](https://user-images.githubusercontent.com/8769819/235808000-3fa5375b-7d70-48b8-8aef-3c1bd17cd6ff.svg)
![unchained_logo](https://user-images.githubusercontent.com/8769819/235808861-32c9cda5-9ad2-4677-adae-48bc6028fe3b.svg)

**Comment by dergigi** [comment]
Thanks for the offer @korpusovmax, but I'll tackle this quickly as time is of the essence. Usually it isn't, so feel free to browse around for other small issues to fix!
